version: '3.7'

services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=db